#!/bin/sh 
echo "Ejecutando Gitleaks para detectar secretos..." 
gitleaks detect --source . --staged 
if [ $? -ne 0 ]; then 
  echo "COMMIT BLOQUEADO: Se encontraron secretos en el codigo." 
  exit 1 
fi 
echo "Sin secretos detectados. Commit permitido." 
exit 0 
